version: '1'
services:
  web:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres_db
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data
    image: postgres:14.2
    ports:
      - "5432:5432"
